/**:
  ros__parameters:
    tolerance: 0.7
    voxel_leaf_size: 0.2
    min_points_number_per_voxel: 2
    min_cluster_size: 2
    max_cluster_size: 2000
    use_height: false
    input_frame: "base_link"
    max_x: 20.0
    min_x: -20.0
    max_y: 20.0
    min_y: -20.0
    max_z: 2.0
    min_z: -0.8
